version: '3.8'

services:
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./data/bridge-indexer-db-data:/var/lib/postgresql/data
      # init schema
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '7512:5432'

  deposit:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      L1_RPC_URL_1 : ${L1_RPC_URL_1}
      L1_RPC_URL_2 : ${L1_RPC_URL_2}
      L1_RPC_URL_3 : ${L1_RPC_URL_3}
      L1_CHAIN_NAME : ${L1_CHAIN_NAME}
      L1_CHAIN_ID : ${L1_CHAIN_ID}
      L1_PORTAL_ADDRESS : ${L1_PORTAL_ADDRESS}
      L1_PORTAL_BLOCK_CREATED : ${L1_PORTAL_BLOCK_CREATED}
      L2_RPC_URL_1 : ${L2_RPC_URL_1}
      L2_RPC_URL_2 : ${L2_RPC_URL_2}
      L2_RPC_URL_3 : ${L2_RPC_URL_3}
      L2_CHAIN_NAME : ${L2_CHAIN_NAME}
      L2_CHAIN_ID : ${L2_CHAIN_ID}
      L2_STANDARD_BRIDGE_ADDRESS : ${L2_STANDARD_BRIDGE_ADDRESS}
      L2_STANDARD_BRIDGE_BLOCK_CREATED : ${L2_STANDARD_BRIDGE_BLOCK_CREATED}
    command: ["./wait-for-it.sh", "db:5432", "--",'npm', 'run', 'deposit']
    stdin_open: true
    tty: true

  withdrawal:
    build: .
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      L1_RPC_URL_1 : ${L1_RPC_URL_1}
      L1_RPC_URL_2 : ${L1_RPC_URL_2}
      L1_RPC_URL_3 : ${L1_RPC_URL_3}
      L1_CHAIN_NAME : ${L1_CHAIN_NAME}
      L1_CHAIN_ID : ${L1_CHAIN_ID}
      L1_PORTAL_ADDRESS : ${L1_PORTAL_ADDRESS}
      L1_PORTAL_BLOCK_CREATED : ${L1_PORTAL_BLOCK_CREATED}
      L2_RPC_URL_1 : ${L2_RPC_URL_1}
      L2_RPC_URL_2 : ${L2_RPC_URL_2}
      L2_RPC_URL_3 : ${L2_RPC_URL_3}
      L2_CHAIN_NAME : ${L2_CHAIN_NAME}
      L2_CHAIN_ID : ${L2_CHAIN_ID}
      L2_STANDARD_BRIDGE_ADDRESS : ${L2_STANDARD_BRIDGE_ADDRESS}
      L2_STANDARD_BRIDGE_BLOCK_CREATED : ${L2_STANDARD_BRIDGE_BLOCK_CREATED}
    command: ["./wait-for-it.sh", "db:5432", "--",'npm', 'run', 'withdrawal']
    stdin_open: true
    tty: true

  server:
    build: .
    restart: unless-stopped
    # volumes:
    #   - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - db
    ports:
      - '3043:3000'
    environment:
      DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    command: ['./wait-for-it.sh', 'db:5432', '--', 'npm', 'run', 'server']
    stdin_open: true
    tty: true
